# Generated by Django 3.0.2 on 2020-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno3', models.CharField(max_length=20)),
                ('lenguage_programacion', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
